packages:
  - apps/*
  - packages/*
  - functions

allowBuilds:
  "@firebase/util": true
  better-sqlite3: true
  electron-winstaller: false
  esbuild: true
  node-datachannel: true
  node-pty: true
  protobufjs: true
  re2: true

patchedDependencies:
  node-pty@1.1.0: patches/node-pty@1.1.0.patch
